parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '%env(DATABASE_VERSION)%'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_general_ci

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            TheFoxUserBundle: ~
            TheFoxPersonsBundle:
                is_bundle: true
                type: annotation
                prefix: 'TheFox\PersonsBundle\Entity'
                alias: TheFoxPersonsBundle
        dql:
            datetime_functions:
                date: DoctrineExtensions\Query\Mysql\Date
                str_to_date: DoctrineExtensions\Query\Mysql\StrToDate
                now: DoctrineExtensions\Query\Mysql\Now
                year: DoctrineExtensions\Query\Mysql\Year
