fos_user:
    db_driver: orm
    firewall_name: main
    from_email:
        address: "%mailer_from_address%"
        sender_name: "%mailer_from_name%"

    service:
        user_manager: sonata.user.orm.user_manager
        mailer: fos_user.mailer.twig_swift

    user_class: TheFox\UserBundle\Entity\User

    # Sonata User
    group:
        group_class: TheFox\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
