framework:
  default_locale: '%locale%'
  translator:
    paths:
      - '%kernel.project_dir%/translations'
#      - '%kernel.project_dir%/src/PersonsBundle/Resources/translations'
    fallbacks:
      - 'en'
