admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    host: '%cms_domain%'
    prefix: /

_sonata_admin:
    resource: .
    type: sonata_admin
    host: '%cms_domain%'
    prefix: /admin

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    host: '%cms_domain%'
    prefix: /

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    host: '%cms_domain%'
    prefix: /resetting
