thefox_persons_frontend_index:
  path: /
  methods: GET
  controller: TheFoxPersonsBundle:Default:default

thefox_persons_frontend_person_list:
  path: /persons
  methods: GET
  controller: TheFoxPersonsBundle:Person:index
