thefox_persons_frontend_index:
  path: /
  methods: GET
  controller: TheFoxPersonsBundle:Default:index

thefox_persons_frontend_dashboard:
  path: /dashboard
  methods: GET
  controller: TheFoxPersonsBundle:Dashboard:index

thefox_persons_frontend_person_list:
  path: /person/list
  methods: GET
  controller: TheFoxPersonsBundle:Person:list

thefox_persons_frontend_person_new:
  path: /person/new
  methods: [GET, POST]
  controller: TheFoxPersonsBundle:Person:new

thefox_persons_frontend_person_new_quick:
  path: /person/new_quick
  methods: [GET, POST]
  controller: TheFoxPersonsBundle:Person:newQuick

thefox_persons_frontend_person_show:
  path: /person/{id}/show
  methods: GET
  controller: TheFoxPersonsBundle:Person:show

thefox_persons_frontend_person_edit:
  path: /person/{id}/edit
  methods: [GET, POST]
  controller: TheFoxPersonsBundle:Person:edit

thefox_persons_frontend_person_delete:
  path: /person/{id}
  methods: DELETE
  controller: TheFoxPersonsBundle:Person:delete

thefox_persons_frontend_event_new:
  path: /event/new
  methods: [GET, POST]
  controller: TheFoxPersonsBundle:Event:new

thefox_persons_frontend_event_show:
  path: /event/{id}/show
  methods: GET
  controller: TheFoxPersonsBundle:Event:show

thefox_persons_frontend_event_edit:
  path: /event/{id}/edit
  methods: [GET, POST]
  controller: TheFoxPersonsBundle:Event:edit

thefox_persons_frontend_event_delete:
  path: /event/{id}
  methods: DELETE
  controller: TheFoxPersonsBundle:Event:delete
